openapi: 3.0.0
info:
  version: 1.0.0
  title: Verteilte Systeme API
  description: API zur Verwaltung von Studenten, Kursen, Dozenten, Bewertungen und mehr.

servers:
  - url: http://localhost:3000
    description: Lokaler Entwicklungsserver

paths:
  /studenten:
    get:
      summary: Alle Studenten abrufen
      responses:
        '200':
          description: Liste aller Studenten
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    studentId:
                      type: integer
                    benutzerId:
                      type: integer
                    studiengang:
                      type: string
                    immatrikulationsTag:
                      type: string
    post:
      summary: Einen neuen Studenten hinzufügen
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                benutzerId:
                  type: integer
                studiengang:
                  type: string
                immatrikulationsTag:
                  type: string
      responses:
        '201':
          description: Student erfolgreich hinzugefügt

  /dozenten:
    get:
      summary: Alle Dozenten abrufen
      responses:
        '200':
          description: Liste aller Dozenten
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    dozentId:
                      type: integer
                    benutzerId:
                      type: integer
                    kurse:
                      type: array
                      items:
                        type: object
                        properties:
                          kursId:
                            type: integer
                    fachgebiet:
                      type: string
    post:
      summary: Einen neuen Dozenten hinzufügen
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                benutzerId:
                  type: integer
                fachgebiet:
                  type: string
                kurse:
                  type: array
                  items:
                    type: object
                    properties:
                      kursId:
                        type: integer
      responses:
        '201':
          description: Dozent erfolgreich hinzugefügt

  /kurse:
    get:
      summary: Alle Kurse abrufen
      responses:
        '200':
          description: Liste aller Kurse
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    kursId:
                      type: integer
                    modulId:
                      type: integer
                    name:
                      type: string
                    startdatum:
                      type: string
                    enddatum:
                      type: string
                    schluessel:
                      type: string
                    status:
                      type: string
                    anzahl:
                      type: integer
    post:
      summary: Einen neuen Kurs hinzufügen
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                modulId:
                  type: integer
                name:
                  type: string
                startdatum:
                  type: string
                enddatum:
                  type: string
                schluessel:
                  type: string
                status:
                  type: string
                anzahl:
                  type: integer
      responses:
        '201':
          description: Kurs erfolgreich hinzugefügt

  /evaluationen:
    get:
      summary: Alle Evaluationen abrufen
      responses:
        '200':
          description: Liste aller Evaluationen
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    evaluationId:
                      type: integer
                    studentId:
                      type: integer
                    kurse:
                      type: array
                      items:
                        type: object
                        properties:
                          kursId:
                            type: integer
                          bewertung:
                            type: integer
    post:
      summary: Eine neue Evaluation hinzufügen
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                studentId:
                  type: integer
                kurse:
                  type: array
                  items:
                    type: object
                    properties:
                      kursId:
                        type: integer
                      bewertung:
                        type: integer
      responses:
        '201':
          description: Evaluation erfolgreich hinzugefügt

  /zertifikate:
    get:
      summary: Alle Zertifikate abrufen
      responses:
        '200':
          description: Liste aller Zertifikate
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    zertifikatId:
                      type: integer
                    kursId:
                      type: integer
    post:
      summary: Ein neues Zertifikat hinzufügen
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                kursId:
                  type: integer
      responses:
        '201':
          description: Zertifikat erfolgreich hinzugefügt

  /einschreibungen:
    get:
      summary: Alle Einschreibungen abrufen
      responses:
        '200':
          description: Liste aller Einschreibungen
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    einschreibungsId:
                      type: integer
                    benutzerId:
                      type: integer
                    kursId:
                      type: integer
                    einschreibedatum:
                      type: string
    post:
      summary: Eine neue Einschreibung hinzufügen
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                benutzerId:
                  type: integer
                kursId:
                  type: integer
                einschreibedatum:
                  type: string
      responses:
        '201':
          description: Einschreibung erfolgreich hinzugefügt

  /benutzer:
      get:
        summary: Alle Benutzer abrufen
        responses:
          '200':
            description: Liste aller Benutzer
            content:
              application/json:
                schema:
                  type: array
                  items:
                    type: object
                    properties:
                      benutzerId:
                        type: integer
                      name:
                        type: string
                      vorname:
                        type: string
                      anmeldename:
                        type: string
                      email:
                        type: string
                      passwort:
                        type: string
                      anmeldedatum:
                        type: string
                      profilbild:
                        type: string
                      geschlecht:
                        type: string
      post:
        summary: Einen neuen Benutzer hinzufügen
        requestBody:
          required: true
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  vorname:
                    type: string
                  anmeldename:
                    type: string
                  email:
                    type: string
                  passwort:
                    type: string
                  anmeldedatum:
                    type: string
                  profilbild:
                    type: string
                  geschlecht:
                    type: string
        responses:
          '201':
            description: Benutzer erfolgreich hinzugefügt

  /assignments:
    get:
      summary: Alle Assignments abrufen
      responses:
        '200':
          description: Liste aller Assignments
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    assignmentId:
                      type: integer
                    name:
                      type: string
                    beschreibung:
                      type: string
    post:
      summary: Ein neues Assignment hinzufügen
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                beschreibung:
                  type: string
      responses:
        '201':
          description: Assignment erfolgreich hinzugefügt

  /aufgaben:
    get:
      summary: Alle Aufgaben abrufen
      responses:
        '200':
          description: Liste aller Aufgaben
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    aufgabeId:
                      type: integer
                    name:
                      type: string
                    beschreibung:
                      type: string
    post:
      summary: Eine neue Aufgabe hinzufügen
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                beschreibung:
                  type: string
      responses:
        '201':
          description: Aufgabe erfolgreich hinzugefügt

  /benachrichtigungen:
    get:
      summary: Alle Benachrichtigungen abrufen
      responses:
        '200':
          description: Liste aller Benachrichtigungen
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    benachrichtigungId:
                      type: integer
                    titel:
                      type: string
                    nachricht:
                      type: string
                    datum:
                      type: string
                    gelesen:
                      type: boolean
    post:
      summary: Eine neue Benachrichtigung hinzufügen
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                titel:
                  type: string
                nachricht:
                  type: string
      responses:
        '201':
          description: Benachrichtigung erfolgreich hinzugefügt

  /bewertungen:
    get:
      summary: Alle Bewertungen abrufen
      responses:
        '200':
          description: Liste aller Bewertungen
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    bewertungId:
                      type: integer
                    studentId:
                      type: integer
                    kursId:
                      type: integer
                    punkte:
                      type: integer
    post:
      summary: Eine neue Bewertung hinzufügen
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                studentId:
                  type: integer
                kursId:
                  type: integer
                punkte:
                  type: integer
      responses:
        '201':
          description: Bewertung erfolgreich hinzugefügt

  /klausuren:
    get:
      summary: Alle Klausuren abrufen
      responses:
        '200':
          description: Liste aller Klausuren
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    klausurId:
                      type: integer
                    kursId:
                      type: integer
                    datum:
                      type: string
                    dauer:
                      type: string
    post:
      summary: Eine neue Klausur hinzufügen
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                kursId:
                  type: integer
                datum:
                  type: string
                dauer:
                  type: string
      responses:
        '201':
          description: Klausur erfolgreich hinzugefügt

  /kursmaterialien:
    get:
      summary: Alle Kursmaterialien abrufen
      responses:
        '200':
          description: Liste aller Kursmaterialien
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    materialId:
                      type: integer
                    name:
                      type: string
                    typ:
                      type: string
                    kursId:
                      type: integer
                    uploadDatum:
                      type: string
    post:
      summary: Neues Kursmaterial hinzufügen
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                typ:
                  type: string
                kursId:
                  type: integer
      responses:
        '201':
          description: Kursmaterial erfolgreich hinzugefügt

  /module:
    get:
      summary: Alle Module abrufen
      responses:
        '200':
          description: Liste aller Module
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    modulId:
                      type: integer
                    name:
                      type: string
                    beschreibung:
                      type: string
    post:
      summary: Ein neues Modul hinzufügen
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                beschreibung:
                  type: string
      responses:
        '201':
          description: Modul erfolgreich hinzugefügt

  /systemadmins:
    get:
      summary: Alle Systemadministratoren abrufen
      responses:
        '200':
          description: Liste aller Systemadministratoren
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    adminId:
                      type: integer
                    name:
                      type: string
                    email:
                      type: string
    post:
      summary: Einen neuen Systemadministrator hinzufügen
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
      responses:
        '201':
          description: Systemadministrator erfolgreich hinzugefügt

  /vorlesungen:
    get:
      summary: Alle Vorlesungen abrufen
      responses:
        '200':
          description: Liste aller Vorlesungen
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    vorlesungId:
                      type: integer
                    kursId:
                      type: integer
                    titel:
                      type: string
                    inhalt:
                      type: string
                    dauer:
                      type: string
    post:
      summary: Eine neue Vorlesung hinzufügen
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                kursId:
                  type: integer
                titel:
                  type: string
                inhalt:
                  type: string
                dauer:
                  type: string
      responses:
        '201':
          description: Vorlesung erfolgreich hinzugefügt