openapi: 3.0.0
info:
  version: 0.1
  title: Course Enrollment API
  description: API to mimic Moodle
paths:
  /kurse:
    get:
      description: Returns all courses
      response:
        '200':
          description: Succesfully returned a list of courses
          content: 
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    course_name:
                      type: string
                    creator:
                      type: string
        '400':
          description: Invalid request
    post:
      description: Create a new course
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                course_name:
                  type: string
                creator:
                  type: string
      responses:
        '200':
          description: Succesfully createda new course
        '400':
          description: Invalid request
  /kurse/{ersteller}:
    get:
      description: Get all courses for a given creator
      parameters:
        - name: creator
          in: path
          required: true
          schema:
            type: string